<?php declare(strict_types=1);

namespace Hyperized\Hostfact\Api\Entity;

use Hyperized\Hostfact\Api\Response\DataBag;

final readonly class Debtor extends Entity
{
    /**
     * @param list<DataBag> $Groups
     * @param list<DataBag> $Translations
     */
    public function __construct(
        DataBag $bag,
        public ?string $Identifier,
        public ?string $DebtorCode,
        public ?string $CompanyName,
        public ?string $CompanyNumber,
        public ?string $LegalForm,
        public ?string $TaxNumber,
        public ?string $Sex,
        public ?string $Initials,
        public ?string $SurName,
        public ?string $Address,
        public ?string $ZipCode,
        public ?string $City,
        public ?string $Country,
        public ?string $EmailAddress,
        public ?string $PhoneNumber,
        public ?string $MobileNumber,
        public ?string $FaxNumber,
        public ?string $Website,
        public ?string $Comment,
        public ?string $InvoiceMethod,
        public ?string $InvoiceCompanyName,
        public ?string $InvoiceSex,
        public ?string $InvoiceInitials,
        public ?string $InvoiceSurName,
        public ?string $InvoiceAddress,
        public ?string $InvoiceZipCode,
        public ?string $InvoiceCity,
        public ?string $InvoiceCountry,
        public ?string $InvoiceEmailAddress,
        public ?string $ReminderEmailAddress,
        public ?string $InvoiceAuthorisation,
        public ?string $MandateID,
        public ?string $InvoiceDataForPriceQuote,
        public ?string $AccountNumber,
        public ?string $AccountBIC,
        public ?string $AccountName,
        public ?string $AccountBank,
        public ?string $AccountCity,
        public ?string $ActiveLogin,
        public ?string $Username,
        public ?string $SecurePassword,
        public ?string $Mailing,
        public ?string $Taxable,
        public ?string $PeriodicInvoiceDays,
        public ?string $InvoiceTemplate,
        public ?string $PriceQuoteTemplate,
        public ?string $ReminderTemplate,
        public ?string $SecondReminderTemplate,
        public ?string $SummationTemplate,
        public ?string $PaymentMail,
        public ?string $PaymentMailTemplate,
        public ?string $InvoiceCollect,
        public ?string $DefaultLanguage,
        public ?string $ClientareaProfile,
        public ?string $Created,
        public ?string $Modified,
        public array $Groups,
        public array $Translations,
    ) {
        parent::__construct($bag);
    }

    public static function fromBag(DataBag $bag): static
    {
        return new self(
            bag: $bag,
            Identifier: $bag->nullableString('Identifier'),
            DebtorCode: $bag->nullableString('DebtorCode'),
            CompanyName: $bag->nullableString('CompanyName'),
            CompanyNumber: $bag->nullableString('CompanyNumber'),
            LegalForm: $bag->nullableString('LegalForm'),
            TaxNumber: $bag->nullableString('TaxNumber'),
            Sex: $bag->nullableString('Sex'),
            Initials: $bag->nullableString('Initials'),
            SurName: $bag->nullableString('SurName'),
            Address: $bag->nullableString('Address'),
            ZipCode: $bag->nullableString('ZipCode'),
            City: $bag->nullableString('City'),
            Country: $bag->nullableString('Country'),
            EmailAddress: $bag->nullableString('EmailAddress'),
            PhoneNumber: $bag->nullableString('PhoneNumber'),
            MobileNumber: $bag->nullableString('MobileNumber'),
            FaxNumber: $bag->nullableString('FaxNumber'),
            Website: $bag->nullableString('Website'),
            Comment: $bag->nullableString('Comment'),
            InvoiceMethod: $bag->nullableString('InvoiceMethod'),
            InvoiceCompanyName: $bag->nullableString('InvoiceCompanyName'),
            InvoiceSex: $bag->nullableString('InvoiceSex'),
            InvoiceInitials: $bag->nullableString('InvoiceInitials'),
            InvoiceSurName: $bag->nullableString('InvoiceSurName'),
            InvoiceAddress: $bag->nullableString('InvoiceAddress'),
            InvoiceZipCode: $bag->nullableString('InvoiceZipCode'),
            InvoiceCity: $bag->nullableString('InvoiceCity'),
            InvoiceCountry: $bag->nullableString('InvoiceCountry'),
            InvoiceEmailAddress: $bag->nullableString('InvoiceEmailAddress'),
            ReminderEmailAddress: $bag->nullableString('ReminderEmailAddress'),
            InvoiceAuthorisation: $bag->nullableString('InvoiceAuthorisation'),
            MandateID: $bag->nullableString('MandateID'),
            InvoiceDataForPriceQuote: $bag->nullableString('InvoiceDataForPriceQuote'),
            AccountNumber: $bag->nullableString('AccountNumber'),
            AccountBIC: $bag->nullableString('AccountBIC'),
            AccountName: $bag->nullableString('AccountName'),
            AccountBank: $bag->nullableString('AccountBank'),
            AccountCity: $bag->nullableString('AccountCity'),
            ActiveLogin: $bag->nullableString('ActiveLogin'),
            Username: $bag->nullableString('Username'),
            SecurePassword: $bag->nullableString('SecurePassword'),
            Mailing: $bag->nullableString('Mailing'),
            Taxable: $bag->nullableString('Taxable'),
            PeriodicInvoiceDays: $bag->nullableString('PeriodicInvoiceDays'),
            InvoiceTemplate: $bag->nullableString('InvoiceTemplate'),
            PriceQuoteTemplate: $bag->nullableString('PriceQuoteTemplate'),
            ReminderTemplate: $bag->nullableString('ReminderTemplate'),
            SecondReminderTemplate: $bag->nullableString('SecondReminderTemplate'),
            SummationTemplate: $bag->nullableString('SummationTemplate'),
            PaymentMail: $bag->nullableString('PaymentMail'),
            PaymentMailTemplate: $bag->nullableString('PaymentMailTemplate'),
            InvoiceCollect: $bag->nullableString('InvoiceCollect'),
            DefaultLanguage: $bag->nullableString('DefaultLanguage'),
            ClientareaProfile: $bag->nullableString('ClientareaProfile'),
            Created: $bag->nullableString('Created'),
            Modified: $bag->nullableString('Modified'),
            Groups: $bag->has('Groups') ? $bag->bags('Groups') : [],
            Translations: $bag->has('Translations') ? $bag->bags('Translations') : [],
        );
    }
}
