pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot

  - name: automatic merge on dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success~=^test*
    actions:
      merge:
        method: merge
